version: '3'

services:
  db:
    build: ./docker/mysql/
    restart: always
    env_file:
      - ./docker/mysql/db-environment.env
    ports:
      - "3306:3306"
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - "db"