version: '3'
#volumes:
 # static_wd volume will be mounted to both nginx and django gunicorn services.
# static:
 # mysql data volume will be mounted to mysql services
# data_volume:

services:
  db:
    build: ./docker/mysql/
#    volumes:
#      - ./data_volume:/var/lib/mysql
    restart: always
    env_file:
      - ./docker/mysql/db-environment.env
    ports:
      - 3306:3306
  web:
    build: .
    volumes:
#      - ./static:/code/static
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
