version: '3'
volumes:
 # static_wd volume will be mounted to both nginx and django gunicorn services.
 static_volume:

services:
  db:
    build: ./docker/mysql/
    restart: always
    env_file:
      - ./docker/mysql/db-environment.env
    ports:
      - 3306:3306
  nginx:
    build: ./docker/nginx/
    ports:
      - 8000:8000
    volumes:
      - static_volume:/code/static
    depends_on:
      - db
    restart: always
  web:
    build: .
    volumes:
      - .:/code
      - static_volume:/code/static
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
