version: '3'

services:
  db:
    build: ./docker/mysql/
    restart: always
    env_file:
      - ./docker/mysql/db-environment.env
    ports:
      - 3306:3306
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
