version: '3'
volumes:
 # static_wd volume will be mounted to both nginx and django gunicorn services.
 static_volume:

services:
  db:
    build: ./docker/mysql/
    restart: always
    env_file:
      - ./docker/mysql/db-environment.env
    ports:
      - 3306:3306
  web:
    build: .
    volumes:
      - static_volume:/code/static
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
